# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trace.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ethereum_pb2 as ethereum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trace.proto',
  package='context.manager',
  syntax='proto3',
  serialized_pb=_b('\n\x0btrace.proto\x12\x0f\x63ontext.manager\x1a\x0e\x65thereum.proto\"&\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"%\n\x05\x43hain\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08isEIP155\x18\x02 \x01(\x08\"&\n\x04\x43\x61ll\x12\x10\n\x08methodId\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t\"&\n\x05\x45rror\x12\x0c\n\x04type\x18\x01 \x01(\x04\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xaf\x02\n\x05Trace\x12(\n\x06sender\x18\x01 \x01(\x0b\x32\x18.context.manager.Account\x12%\n\x05\x63hain\x18\x02 \x01(\x0b\x32\x16.context.manager.Chain\x12*\n\x08receiver\x18\x03 \x01(\x0b\x32\x18.context.manager.Account\x12#\n\x04\x63\x61ll\x18\x04 \x01(\x0b\x32\x15.context.manager.Call\x12\x31\n\x0btransaction\x18\x05 \x01(\x0b\x32\x1c.context.manager.Transaction\x12)\n\x07receipt\x18\x06 \x01(\x0b\x32\x18.context.manager.Receipt\x12&\n\x06\x65rrors\x18\x07 \x03(\x0b\x32\x16.context.manager.ErrorBCZAgitlab.com/ConsenSys/client/fr/core-stack/core.git/protobuf/traceb\x06proto3')
  ,
  dependencies=[ethereum__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='context.manager.Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='context.manager.Account.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='context.manager.Account.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=86,
)


_CHAIN = _descriptor.Descriptor(
  name='Chain',
  full_name='context.manager.Chain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='context.manager.Chain.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isEIP155', full_name='context.manager.Chain.isEIP155', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=125,
)


_CALL = _descriptor.Descriptor(
  name='Call',
  full_name='context.manager.Call',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='methodId', full_name='context.manager.Call.methodId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='args', full_name='context.manager.Call.args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=165,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='context.manager.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='context.manager.Error.type', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='context.manager.Error.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=205,
)


_TRACE = _descriptor.Descriptor(
  name='Trace',
  full_name='context.manager.Trace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='context.manager.Trace.sender', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chain', full_name='context.manager.Trace.chain', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='context.manager.Trace.receiver', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='call', full_name='context.manager.Trace.call', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='context.manager.Trace.transaction', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receipt', full_name='context.manager.Trace.receipt', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errors', full_name='context.manager.Trace.errors', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=511,
)

_TRACE.fields_by_name['sender'].message_type = _ACCOUNT
_TRACE.fields_by_name['chain'].message_type = _CHAIN
_TRACE.fields_by_name['receiver'].message_type = _ACCOUNT
_TRACE.fields_by_name['call'].message_type = _CALL
_TRACE.fields_by_name['transaction'].message_type = ethereum__pb2._TRANSACTION
_TRACE.fields_by_name['receipt'].message_type = ethereum__pb2._RECEIPT
_TRACE.fields_by_name['errors'].message_type = _ERROR
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
DESCRIPTOR.message_types_by_name['Chain'] = _CHAIN
DESCRIPTOR.message_types_by_name['Call'] = _CALL
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['Trace'] = _TRACE

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNT,
  __module__ = 'trace_pb2'
  # @@protoc_insertion_point(class_scope:context.manager.Account)
  ))
_sym_db.RegisterMessage(Account)

Chain = _reflection.GeneratedProtocolMessageType('Chain', (_message.Message,), dict(
  DESCRIPTOR = _CHAIN,
  __module__ = 'trace_pb2'
  # @@protoc_insertion_point(class_scope:context.manager.Chain)
  ))
_sym_db.RegisterMessage(Chain)

Call = _reflection.GeneratedProtocolMessageType('Call', (_message.Message,), dict(
  DESCRIPTOR = _CALL,
  __module__ = 'trace_pb2'
  # @@protoc_insertion_point(class_scope:context.manager.Call)
  ))
_sym_db.RegisterMessage(Call)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'trace_pb2'
  # @@protoc_insertion_point(class_scope:context.manager.Error)
  ))
_sym_db.RegisterMessage(Error)

Trace = _reflection.GeneratedProtocolMessageType('Trace', (_message.Message,), dict(
  DESCRIPTOR = _TRACE,
  __module__ = 'trace_pb2'
  # @@protoc_insertion_point(class_scope:context.manager.Trace)
  ))
_sym_db.RegisterMessage(Trace)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('ZAgitlab.com/ConsenSys/client/fr/core-stack/core.git/protobuf/trace'))
# @@protoc_insertion_point(module_scope)