// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/types/tx/tx.proto

package tx

import (
	"fmt"
	"math"

	"github.com/golang/protobuf/proto"
	error1 "gitlab.com/ConsenSys/client/fr/core-stack/orchestrate.git/pkg/types/error"
	"gitlab.com/ConsenSys/client/fr/core-stack/orchestrate.git/pkg/types/ethereum"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Method int32

const (
	// Classic Ethereum Transaction
	Method_ETH_SENDRAWTRANSACTION Method = 0
	// Quorum Constellation
	Method_ETH_SENDPRIVATETRANSACTION Method = 1
	// Quorum Tessera
	Method_ETH_SENDRAWPRIVATETRANSACTION Method = 2
	// Besu Orion
	Method_EEA_SENDPRIVATETRANSACTION Method = 3
)

var Method_name = map[int32]string{
	0: "ETH_SENDRAWTRANSACTION",
	1: "ETH_SENDPRIVATETRANSACTION",
	2: "ETH_SENDRAWPRIVATETRANSACTION",
	3: "EEA_SENDPRIVATETRANSACTION",
}

var Method_value = map[string]int32{
	"ETH_SENDRAWTRANSACTION":        0,
	"ETH_SENDPRIVATETRANSACTION":    1,
	"ETH_SENDRAWPRIVATETRANSACTION": 2,
	"EEA_SENDPRIVATETRANSACTION":    3,
}

func (x Method) String() string {
	return proto.EnumName(Method_name, int32(x))
}

func (Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be952cdce9bc3bdf, []int{0}
}

type JobType int32

const (
	JobType_ETH_TX                 JobType = 0
	JobType_ETH_RAW_TX             JobType = 1
	JobType_ETH_ORION_MARKING_TX   JobType = 2
	JobType_ETH_ORION_EEA_TX       JobType = 3
	JobType_ETH_TESSERA_MARKING_TX JobType = 4
	JobType_ETH_TESSERA_PRIVATE_TX JobType = 5
)

var JobType_name = map[int32]string{
	0: "ETH_TX",
	1: "ETH_RAW_TX",
	2: "ETH_ORION_MARKING_TX",
	3: "ETH_ORION_EEA_TX",
	4: "ETH_TESSERA_MARKING_TX",
	5: "ETH_TESSERA_PRIVATE_TX",
}

var JobType_value = map[string]int32{
	"ETH_TX":                 0,
	"ETH_RAW_TX":             1,
	"ETH_ORION_MARKING_TX":   2,
	"ETH_ORION_EEA_TX":       3,
	"ETH_TESSERA_MARKING_TX":  4,
	"ETH_TESSERA_PRIVATE_TX": 5,
}

func (x JobType) String() string {
	return proto.EnumName(JobType_name, int32(x))
}

func (JobType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be952cdce9bc3bdf, []int{1}
}

type TxRequest struct {
	// Technical header (optional)
	Headers map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Name of the Chain as registered on the chain registry
	// e.g. 1 for mainnet, 3 for Ropsten
	Chain string `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	// Type of a protocol that should be used
	Method Method `protobuf:"varint,3,opt,name=method,proto3,enum=tx.Method" json:"method,omitempty"`
	// Params for the transaction
	Params *Params `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	// ID of the Request in UUID RFC 4122, ISO/IEC 9834-8:2005 format
	// e.g a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
	Id string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	// [option]
	ContextLabels map[string]string `protobuf:"bytes,6,rep,name=context_labels,json=contextLabels,proto3" json:"context_labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Type of the job
	JobType              JobType  `protobuf:"varint,7,opt,name=jobType,proto3,enum=tx.JobType" json:"jobType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxRequest) Reset()         { *m = TxRequest{} }
func (m *TxRequest) String() string { return proto.CompactTextString(m) }
func (*TxRequest) ProtoMessage()    {}
func (*TxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be952cdce9bc3bdf, []int{0}
}

func (m *TxRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxRequest.Unmarshal(m, b)
}
func (m *TxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxRequest.Marshal(b, m, deterministic)
}
func (m *TxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRequest.Merge(m, src)
}
func (m *TxRequest) XXX_Size() int {
	return xxx_messageInfo_TxRequest.Size(m)
}
func (m *TxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxRequest proto.InternalMessageInfo

func (m *TxRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *TxRequest) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *TxRequest) GetMethod() Method {
	if m != nil {
		return m.Method
	}
	return Method_ETH_SENDRAWTRANSACTION
}

func (m *TxRequest) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *TxRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TxRequest) GetContextLabels() map[string]string {
	if m != nil {
		return m.ContextLabels
	}
	return nil
}

func (m *TxRequest) GetJobType() JobType {
	if m != nil {
		return m.JobType
	}
	return JobType_ETH_TX
}

type TxEnvelope struct {
	// Types that are valid to be assigned to Msg:
	//	*TxEnvelope_TxRequest
	//	*TxEnvelope_TxResponse
	Msg                  isTxEnvelope_Msg  `protobuf_oneof:"msg"`
	InternalLabels       map[string]string `protobuf:"bytes,1,rep,name=internal_labels,json=internalLabels,proto3" json:"internal_labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TxEnvelope) Reset()         { *m = TxEnvelope{} }
func (m *TxEnvelope) String() string { return proto.CompactTextString(m) }
func (*TxEnvelope) ProtoMessage()    {}
func (*TxEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_be952cdce9bc3bdf, []int{1}
}

func (m *TxEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxEnvelope.Unmarshal(m, b)
}
func (m *TxEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxEnvelope.Marshal(b, m, deterministic)
}
func (m *TxEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxEnvelope.Merge(m, src)
}
func (m *TxEnvelope) XXX_Size() int {
	return xxx_messageInfo_TxEnvelope.Size(m)
}
func (m *TxEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_TxEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_TxEnvelope proto.InternalMessageInfo

type isTxEnvelope_Msg interface {
	isTxEnvelope_Msg()
}

type TxEnvelope_TxRequest struct {
	TxRequest *TxRequest `protobuf:"bytes,2,opt,name=tx_request,json=txRequest,proto3,oneof"`
}

type TxEnvelope_TxResponse struct {
	TxResponse *TxResponse `protobuf:"bytes,3,opt,name=tx_response,json=txResponse,proto3,oneof"`
}

func (*TxEnvelope_TxRequest) isTxEnvelope_Msg() {}

func (*TxEnvelope_TxResponse) isTxEnvelope_Msg() {}

func (m *TxEnvelope) GetMsg() isTxEnvelope_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *TxEnvelope) GetTxRequest() *TxRequest {
	if x, ok := m.GetMsg().(*TxEnvelope_TxRequest); ok {
		return x.TxRequest
	}
	return nil
}

func (m *TxEnvelope) GetTxResponse() *TxResponse {
	if x, ok := m.GetMsg().(*TxEnvelope_TxResponse); ok {
		return x.TxResponse
	}
	return nil
}

func (m *TxEnvelope) GetInternalLabels() map[string]string {
	if m != nil {
		return m.InternalLabels
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TxEnvelope) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TxEnvelope_TxRequest)(nil),
		(*TxEnvelope_TxResponse)(nil),
	}
}

type Params struct {
	// Sender of the transaction - Ethereum Account Address
	// e.g 0xAf84242d70aE9D268E2bE3616ED497BA28A7b62C
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// The address of the receiver. null when it’s a contract creation transaction.
	// e.g. 0xAf84242d70aE9D268E2bE3616ED497BA28A7b62C
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Integer of the gas provided for the transaction execution.
	Gas string `protobuf:"bytes,4,opt,name=gas,proto3" json:"gas,omitempty"`
	// Integer of the gas price used for each paid gas.
	// e.g 0xaf23b
	GasPrice string `protobuf:"bytes,5,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	// Integer of the value sent with this transaction.
	// e.g 0xaf23
	Value string `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	// Integer of a nonce.
	Nonce string `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Hash of the method signature (4 bytes) followed by encoded parameters.
	// e.g 0xa9059cbb000000000000000000000000ff778b716fc07d98839f48ddb88d8be583beb684000000000000000000000000000000000000000000000000002386f26fc10000
	Data string `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	// Contract identifier
	// e.g. "ERC20[v1.0.0]"
	Contract string `protobuf:"bytes,9,opt,name=contract,proto3" json:"contract,omitempty"`
	// Signature of the method to call on contract
	// e.g "transfer(address,uint256)"
	MethodSignature string `protobuf:"bytes,10,opt,name=method_signature,json=methodSignature,proto3" json:"method_signature,omitempty"`
	// Arguments to feed on transaction call
	Args []string `protobuf:"bytes,11,rep,name=args,proto3" json:"args,omitempty"`
	// The signed, RLP encoded transaction
	Raw                  string   `protobuf:"bytes,12,opt,name=raw,proto3" json:"raw,omitempty"`
	PrivateFor           []string `protobuf:"bytes,13,rep,name=private_for,json=privateFor,proto3" json:"private_for,omitempty"`
	PrivateFrom          string   `protobuf:"bytes,14,opt,name=private_from,json=privateFrom,proto3" json:"private_from,omitempty"`
	PrivateTxType        string   `protobuf:"bytes,15,opt,name=private_tx_type,json=privateTxType,proto3" json:"private_tx_type,omitempty"`
	PrivacyGroupId       string   `protobuf:"bytes,16,opt,name=privacy_group_id,json=privacyGroupId,proto3" json:"privacy_group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_be952cdce9bc3bdf, []int{2}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Params) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Params) GetGas() string {
	if m != nil {
		return m.Gas
	}
	return ""
}

func (m *Params) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *Params) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Params) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Params) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Params) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Params) GetMethodSignature() string {
	if m != nil {
		return m.MethodSignature
	}
	return ""
}

func (m *Params) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Params) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

func (m *Params) GetPrivateFor() []string {
	if m != nil {
		return m.PrivateFor
	}
	return nil
}

func (m *Params) GetPrivateFrom() string {
	if m != nil {
		return m.PrivateFrom
	}
	return ""
}

func (m *Params) GetPrivateTxType() string {
	if m != nil {
		return m.PrivateTxType
	}
	return ""
}

func (m *Params) GetPrivacyGroupId() string {
	if m != nil {
		return m.PrivacyGroupId
	}
	return ""
}

type TxResponse struct {
	// Extra information (optional)
	Headers map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// ID of the Response in UUID RFC 4122, ISO/IEC 9834-8:2005 format
	// e.g a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// [option]
	ContextLabels map[string]string     `protobuf:"bytes,3,rep,name=context_labels,json=contextLabels,proto3" json:"context_labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Transaction   *ethereum.Transaction `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Receipt       *ethereum.Receipt     `protobuf:"bytes,5,opt,name=receipt,proto3" json:"receipt,omitempty"`
	// Name of the Chain as registered on the chain registry
	// e.g. 1 for mainnet, 3 for Ropsten
	Chain                string          `protobuf:"bytes,7,opt,name=chain,proto3" json:"chain,omitempty"`
	Errors               []*error1.Error `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TxResponse) Reset()         { *m = TxResponse{} }
func (m *TxResponse) String() string { return proto.CompactTextString(m) }
func (*TxResponse) ProtoMessage()    {}
func (*TxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be952cdce9bc3bdf, []int{3}
}

func (m *TxResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxResponse.Unmarshal(m, b)
}
func (m *TxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxResponse.Marshal(b, m, deterministic)
}
func (m *TxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxResponse.Merge(m, src)
}
func (m *TxResponse) XXX_Size() int {
	return xxx_messageInfo_TxResponse.Size(m)
}
func (m *TxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxResponse proto.InternalMessageInfo

func (m *TxResponse) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *TxResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TxResponse) GetContextLabels() map[string]string {
	if m != nil {
		return m.ContextLabels
	}
	return nil
}

func (m *TxResponse) GetTransaction() *ethereum.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *TxResponse) GetReceipt() *ethereum.Receipt {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *TxResponse) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *TxResponse) GetErrors() []*error1.Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterEnum("tx.Method", Method_name, Method_value)
	proto.RegisterEnum("tx.JobType", JobType_name, JobType_value)
	proto.RegisterType((*TxRequest)(nil), "tx.TxRequest")
	proto.RegisterMapType((map[string]string)(nil), "tx.TxRequest.ContextLabelsEntry")
	proto.RegisterMapType((map[string]string)(nil), "tx.TxRequest.HeadersEntry")
	proto.RegisterType((*TxEnvelope)(nil), "tx.TxEnvelope")
	proto.RegisterMapType((map[string]string)(nil), "tx.TxEnvelope.InternalLabelsEntry")
	proto.RegisterType((*Params)(nil), "tx.Params")
	proto.RegisterType((*TxResponse)(nil), "tx.TxResponse")
	proto.RegisterMapType((map[string]string)(nil), "tx.TxResponse.ContextLabelsEntry")
	proto.RegisterMapType((map[string]string)(nil), "tx.TxResponse.HeadersEntry")
}

func init() {
	proto.RegisterFile("pkg/types/tx/tx.proto", fileDescriptor_be952cdce9bc3bdf)
}

var fileDescriptor_be952cdce9bc3bdf = []byte{
	// 932 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xd1, 0x72, 0xe3, 0x34,
	0x17, 0xae, 0xed, 0x36, 0x69, 0x8e, 0xdb, 0x34, 0xbf, 0xfe, 0x96, 0x31, 0xe9, 0x00, 0x69, 0x66,
	0x61, 0xca, 0x32, 0xd8, 0x43, 0x81, 0x81, 0xd9, 0x2b, 0xd2, 0x92, 0x36, 0x61, 0x77, 0xd3, 0x8e,
	0x62, 0xd8, 0x1d, 0x6e, 0x3c, 0xaa, 0xa3, 0x3a, 0xa6, 0x89, 0x65, 0x64, 0xa5, 0xeb, 0xbc, 0x00,
	0xdc, 0xf0, 0x0a, 0xf0, 0x26, 0xbc, 0x1b, 0x23, 0xc9, 0x4e, 0xdc, 0xdd, 0xee, 0x30, 0x7b, 0xc5,
	0x4d, 0x46, 0x3a, 0xdf, 0x77, 0x8e, 0xce, 0x51, 0x3e, 0x7d, 0x86, 0x83, 0xf4, 0x36, 0xf2, 0xc4,
	0x32, 0xa5, 0x99, 0x27, 0x72, 0x4f, 0xe4, 0x6e, 0xca, 0x99, 0x60, 0xc8, 0x14, 0x79, 0xfb, 0x70,
	0x0d, 0x51, 0xce, 0x19, 0xd7, 0xbf, 0x9a, 0xd0, 0xee, 0x54, 0x40, 0x31, 0xa5, 0x9c, 0x2e, 0xe6,
	0x1e, 0xa7, 0x21, 0x8d, 0x53, 0x51, 0x30, 0x1e, 0x3d, 0xc0, 0x10, 0x9c, 0x24, 0x19, 0x09, 0x45,
	0xcc, 0x12, 0xcd, 0xea, 0xfe, 0x69, 0x41, 0xc3, 0xcf, 0x31, 0xfd, 0x75, 0x41, 0x33, 0x81, 0xbe,
	0x82, 0xfa, 0x94, 0x92, 0x09, 0xe5, 0x99, 0x63, 0x74, 0xac, 0x63, 0xfb, 0xa4, 0xed, 0x8a, 0xdc,
	0x5d, 0xe1, 0xee, 0x40, 0x83, 0xfd, 0x44, 0xf0, 0x25, 0x2e, 0xa9, 0x68, 0x1f, 0xb6, 0xc2, 0x29,
	0x89, 0x13, 0xc7, 0xec, 0x18, 0xc7, 0x0d, 0xac, 0x37, 0xa8, 0x0b, 0xb5, 0x39, 0x15, 0x53, 0x36,
	0x71, 0xac, 0x8e, 0x71, 0xdc, 0x3c, 0x01, 0x59, 0xea, 0xb9, 0x8a, 0xe0, 0x02, 0x91, 0x9c, 0x94,
	0x70, 0x32, 0xcf, 0x9c, 0xcd, 0x8e, 0x71, 0x6c, 0x6b, 0xce, 0x95, 0x8a, 0xe0, 0x02, 0x41, 0x4d,
	0x30, 0xe3, 0x89, 0xb3, 0xa5, 0x4a, 0x9b, 0xf1, 0x04, 0x5d, 0x40, 0x33, 0x64, 0x89, 0xa0, 0xb9,
	0x08, 0x66, 0xe4, 0x9a, 0xce, 0x32, 0xa7, 0xa6, 0x5a, 0xed, 0xdc, 0x6f, 0xf5, 0x4c, 0x73, 0x9e,
	0x29, 0x8a, 0x6e, 0x78, 0x37, 0xac, 0xc6, 0xd0, 0xc7, 0x50, 0xff, 0x85, 0x5d, 0xfb, 0xcb, 0x94,
	0x3a, 0x75, 0xd5, 0xa1, 0x2d, 0x2b, 0xfc, 0xa0, 0x43, 0xb8, 0xc4, 0xda, 0x4f, 0x60, 0xa7, 0x3a,
	0x36, 0x6a, 0x81, 0x75, 0x4b, 0x97, 0x8e, 0xa1, 0x1a, 0x92, 0x4b, 0x39, 0xff, 0x1d, 0x99, 0x2d,
	0x68, 0x39, 0xbf, 0xda, 0x3c, 0x31, 0xbf, 0x35, 0xda, 0xdf, 0x01, 0x7a, 0xb3, 0x8f, 0x77, 0xa9,
	0xd0, 0xfd, 0xcd, 0x04, 0xf0, 0xf3, 0x7e, 0x72, 0x47, 0x67, 0x2c, 0xa5, 0xc8, 0x05, 0x10, 0x79,
	0xc0, 0xf5, 0x8c, 0x8a, 0x6d, 0x9f, 0xec, 0xde, 0x1b, 0x7c, 0xb0, 0x81, 0x1b, 0x62, 0xf5, 0x87,
	0x7e, 0x01, 0xb6, 0xe2, 0x67, 0x29, 0x4b, 0x32, 0xaa, 0xfe, 0x09, 0xfb, 0xa4, 0x59, 0x26, 0xe8,
	0xe8, 0x60, 0x03, 0x83, 0x58, 0xed, 0xd0, 0x53, 0xd8, 0x8b, 0x13, 0x41, 0x79, 0x42, 0x66, 0xe5,
	0x05, 0x6b, 0x2d, 0x74, 0x75, 0x5a, 0xd9, 0x8b, 0x3b, 0x2c, 0x58, 0xd5, 0x2b, 0x6e, 0xc6, 0xf7,
	0x82, 0xed, 0x1e, 0xfc, 0xff, 0x01, 0xda, 0xbb, 0xdc, 0xc0, 0xe9, 0x16, 0x58, 0xf3, 0x2c, 0xea,
	0xfe, 0x65, 0x41, 0x4d, 0x2b, 0x03, 0x21, 0xd8, 0xbc, 0xe1, 0x6c, 0x5e, 0xa4, 0xab, 0xb5, 0x54,
	0x89, 0x60, 0x45, 0xb2, 0x29, 0x98, 0x3c, 0x21, 0x22, 0x5a, 0x56, 0x0d, 0x2c, 0x97, 0xe8, 0x10,
	0x1a, 0x11, 0xc9, 0x82, 0x94, 0xc7, 0x21, 0x2d, 0xe4, 0xb4, 0x1d, 0x91, 0xec, 0x4a, 0xee, 0xd7,
	0xc7, 0xd7, 0x2a, 0xc7, 0xcb, 0x68, 0xc2, 0x92, 0x50, 0xeb, 0xa3, 0x81, 0xf5, 0x46, 0x1e, 0x3f,
	0x21, 0x82, 0x38, 0xdb, 0xfa, 0x78, 0xb9, 0x46, 0x6d, 0xd8, 0x96, 0xe2, 0xe2, 0x24, 0x14, 0x4e,
	0x43, 0xd7, 0x2e, 0xf7, 0xe8, 0x53, 0x68, 0x69, 0xb9, 0x07, 0x59, 0x1c, 0x25, 0x44, 0x2c, 0x38,
	0x75, 0x40, 0x71, 0xf6, 0x74, 0x7c, 0x5c, 0x86, 0x65, 0x69, 0xc2, 0xa3, 0xcc, 0xb1, 0x3b, 0x96,
	0x2c, 0x2d, 0xd7, 0x72, 0x12, 0x4e, 0x5e, 0x39, 0x3b, 0x7a, 0x12, 0x4e, 0x5e, 0xa1, 0x8f, 0xc0,
	0x4e, 0x79, 0x7c, 0x47, 0x04, 0x0d, 0x6e, 0x18, 0x77, 0x76, 0x15, 0x19, 0x8a, 0xd0, 0x39, 0xe3,
	0xe8, 0x08, 0x76, 0x56, 0x04, 0x79, 0x51, 0x4d, 0x95, 0x5b, 0x26, 0x9d, 0xcb, 0xfb, 0xfa, 0x04,
	0xf6, 0x4a, 0x8a, 0xc8, 0x03, 0x69, 0x13, 0xce, 0x9e, 0x62, 0xed, 0x16, 0x61, 0x3f, 0x97, 0xea,
	0x47, 0xc7, 0xd0, 0x52, 0x81, 0x70, 0x19, 0x44, 0x9c, 0x2d, 0xd2, 0x20, 0x9e, 0x38, 0x2d, 0x45,
	0x6c, 0x16, 0xf1, 0x0b, 0x19, 0x1e, 0x4e, 0xba, 0x7f, 0x5b, 0x52, 0xa9, 0x2b, 0x19, 0x7d, 0xfd,
	0xba, 0x95, 0x1c, 0xde, 0x57, 0xdd, 0x5b, 0xbc, 0x44, 0xbf, 0x76, 0x73, 0xf5, 0xda, 0x07, 0x6f,
	0xbc, 0x76, 0x4b, 0x55, 0x3b, 0x7a, 0xad, 0xda, 0xbf, 0x3f, 0xf7, 0x6f, 0xc0, 0xae, 0xd8, 0x5f,
	0x61, 0x38, 0x07, 0x6e, 0xe9, 0x8d, 0xae, 0xbf, 0x06, 0x71, 0x95, 0x89, 0x3e, 0x83, 0x7a, 0xe1,
	0xac, 0x4a, 0x36, 0xf6, 0xc9, 0xff, 0xd6, 0x49, 0x58, 0x03, 0xb8, 0x64, 0xac, 0xbd, 0xb0, 0x5e,
	0xf5, 0xc2, 0x47, 0x50, 0x53, 0xe6, 0x5d, 0x7a, 0xd5, 0x8e, 0xab, 0xbd, 0xbc, 0x2f, 0x7f, 0x71,
	0x81, 0xfd, 0xb7, 0x4e, 0xf3, 0xf8, 0x77, 0x03, 0x6a, 0xda, 0x9e, 0x51, 0x1b, 0xde, 0xeb, 0xfb,
	0x83, 0x60, 0xdc, 0x1f, 0x7d, 0x8f, 0x7b, 0x2f, 0x7c, 0xdc, 0x1b, 0x8d, 0x7b, 0x67, 0xfe, 0xf0,
	0x72, 0xd4, 0xda, 0x40, 0x1f, 0x42, 0xbb, 0xc4, 0xae, 0xf0, 0xf0, 0xa7, 0x9e, 0xdf, 0xaf, 0xe2,
	0x06, 0x3a, 0x82, 0x0f, 0x2a, 0xb9, 0x0f, 0x50, 0x4c, 0x55, 0xa2, 0xdf, 0x7b, 0x5b, 0x09, 0xeb,
	0xf1, 0x1f, 0x06, 0xd4, 0x0b, 0x1b, 0x46, 0x00, 0x35, 0x59, 0xce, 0x7f, 0xd9, 0xda, 0x40, 0x4d,
	0x00, 0xb9, 0xc6, 0xbd, 0x17, 0x72, 0x6f, 0x20, 0x07, 0xf6, 0xe5, 0xfe, 0x12, 0x0f, 0x2f, 0x47,
	0xc1, 0xf3, 0x1e, 0x7e, 0x3a, 0x1c, 0x5d, 0x48, 0xc4, 0x44, 0xfb, 0xd0, 0x5a, 0x23, 0xf2, 0x2c,
	0xff, 0x65, 0xcb, 0x42, 0xef, 0xc3, 0x81, 0xaa, 0xd5, 0x1f, 0x8f, 0xfb, 0xb8, 0x17, 0x5c, 0xfd,
	0x78, 0xfa, 0x6c, 0x78, 0x26, 0xa1, 0xcd, 0x72, 0xe2, 0x15, 0xa4, 0xdb, 0x92, 0xd8, 0xd6, 0xe9,
	0xe0, 0xe7, 0xf3, 0x28, 0x16, 0x33, 0x72, 0xed, 0x86, 0x6c, 0xee, 0x9d, 0x49, 0xb9, 0x25, 0xe3,
	0x65, 0xe6, 0x85, 0xb3, 0x98, 0x26, 0xc2, 0xbb, 0xe1, 0x5e, 0xc8, 0x38, 0xfd, 0x3c, 0x13, 0x24,
	0xbc, 0xf5, 0x18, 0x0f, 0xa7, 0x34, 0x13, 0x9c, 0x08, 0xea, 0x46, 0xb1, 0xf0, 0xaa, 0x9f, 0xf7,
	0xeb, 0x9a, 0xfa, 0xe6, 0x7e, 0xf9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xef, 0xc0, 0x8c,
	0xf5, 0x07, 0x00, 0x00,
}
