version: '3.7'

services:
  report:
    build:
      context: .
    environment:
      METADATA_TAG: ${CI_COMMIT_TAG-}
      METADATA_BRANCH: ${CI_COMMIT_BRANCH-}
      METADATA_COMMIT: ${CI_COMMIT_SHORT_SHA-}
      METADATA_OS: ${CI_RUNNER_EXECUTABLE_ARCH-}
      METADATA_RUNNER: ${CI_RUNNER_DESCRIPTION-}
      METADATA_RUNNER_ID: ${CI_RUNNER_ID-}
      METADATA_RUNNER_VERSION: ${CI_RUNNER_REVISION-}
    volumes:
      - ../../build/report:/use/src/app/in
      - ../../build/report:/use/src/app/out
