---
stages:
  - cache-update
  - test
  - build

variables:
  GOPATH: ${CI_PROJECT_DIR}/.gocache
  ARTIFACT_DOWNLOAD_ATTEMPTS: 5
  RESTORE_CACHE_ATTEMPTS: 5
  # CI_DEBUG_TRACE: "true"

services:
  - docker:18-dind

before_script:
  # Change git config so we can import go packages from GitLab
  - git config --global --add url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "git@gitlab.com:"
  - git config --global --add url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"

  # Set GOPATH
  - mkdir -p ${GOPATH}
  - export PATH="${PATH}:${GOPATH}/bin:${GOROOT}/bin"
  - make tools

cache-update:
  image: golang:1.12
  stage: cache-update
  script:
    - go mod download -json
  cache:
    policy: push
    paths:
      - ${GOPATH}
  only:
    - master

test:
  image: golang:1.12
  stage: test
  coverage: /^total:.*\s(\d+.\d+)%/
  script:
    - make run-coverage
  services:
    - postgres:10.7-alpine
  variables:
    DB_HOST: "postgres"
  cache:
    policy: pull
    paths:
      - ${GOPATH}
  except:
      - tags

lint:
  image: golang:1.12
  stage: test
  script:
    - make race
    - make lint
  cache:
    policy: pull
    paths:
      - ${GOPATH}
  except:
      - tags
