# Use latest Golang image for new perks and shiny features
image: golang:latest

stages:
  - test

test:
  stage: test
  coverage: /^total:.*\s(\d+.\d+)%/
  before_script:
    - mkdir "${HOME}/go"; export GOPATH="${HOME}/go"
    - export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"
    - make tools
  script:
    - make run-coverage

test-lint:
  stage: test
  before_script:
    - mkdir "${HOME}/go"; export GOPATH="${HOME}/go"
    - export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"
    - make tools
  script:
    - make fmt-check
    - make misspell-check
    - make lint