# Use latest Golang image for new perks and shiny features
image: golang:latest

cache:
  paths:
    - /apt-cache
    - /go/src/

stages:
  - install
  - test

install:
  stage: install
  script:
    - mkdir "${HOME}/go"; export GOPATH="${HOME}/go"
    - export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"
    - make tools

test:
  stage: test
  coverage: /^total:.*\s(\d+.\d+)%/
  script:
    - make run-coverage

test-lint:
  stage: test
  script:
    - make fmt-check
    - make misspell-check
    - make lint