# Use latest Golang image for new perks and shiny features
image: golang:latest

cache:
  paths:
    - /apt-cache
    - /root/go

stages:
  - test

before_script:
  - eval $(ssh-agent -s)
  - echo "$DEPLOY_SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ls ${HOME}/.ssh
  - ssh-keyscan -H 'https://gitlab.com' >> ${HOME}/.ssh/known_hosts
  - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - git clone https://gitlab.com/ConsenSys/client/fr/core-stack/infra/striped-mutex.git
  - echo "${HOME}/go"
  - mkdir "${HOME}/go"; export GOPATH="${HOME}/go"
  - export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"
  - make tools

test:
  stage: test
  coverage: /^total:.*\s(\d+.\d+)%/
  script:
    - make run-coverage

test-lint:
  stage: test
  script:
    - make fmt-check
    - make misspell-check
    - make race
    - make lint