# Use latest Golang image for new perks and shiny features
image: golang:latest

cache:
  paths:
    - /apt-cache
    - /root/go

stages:
  - test

before_script:
  # - eval $(ssh-agent -s)
  # - echo "$SSH_DEPLOY_CORE_STACK" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - echo "$SSH_DEPLOY_CORE_STACK"
  - echo "$SSH_DEPLOY_CORE_STACK" | tr -d '\r' > ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  # - ssh-keygen -R gitlab.com
  # - eval "$(ssh-agent -s)"
  # - ssh-add ~/.ssh/id_rsa
  - git config --global user.email "deployer@core-stack.com"
  - git config --global user.name "Deployer"
  - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
  - git clone git@gitlab.com:ConsenSys/client/fr/core-stack/infra/striped-mutex.git
  # - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/" 
  - echo "${HOME}/go"
  - mkdir "${HOME}/go"; export GOPATH="${HOME}/go"
  - export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"
  - make tools

test:
  stage: test
  coverage: /^total:.*\s(\d+.\d+)%/
  script:
    - make run-coverage

test-lint:
  stage: test
  script:
    - make fmt-check
    - make misspell-check
    - make race
    - make lint