codecov:
  notify:
    require_ci_to_pass: no

coverage:
  range: 40..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 80%
        # Allow decreasing 2% of total coverage to avoid noise.
        threshold: 2%
        informational: true
        flags:
          - unittests
          - integration
        paths:
          - "src"
          - "pkg"
          - "cmd"
          - "!*/mock"
          - "!*/mocks"
          - "!*/testutils"
          - "!*/testdata"
          - "!tests/*"
          - "!*/integration-tests"
    patch:
      default:
        target: 90%
        threshold: 1%
        only_pulls: true
        informational: true
        flags:
          - unittests
          - integration
        paths:
          - "src"
          - "pkg"
          - "cmd"
          - "!*/mock"
          - "!*/mocks"
          - "!*/testutils"
          - "!tests/*"
          - "!*/integration-tests"

comment:
  layout: "reach, diff, flags"
  behavior: default
  require_changes: no

github_checks:
    annotations: true
    
ignore:
  - tests/*
  - main.go
  - "*/testutils"
  - "*/mock"
  - "*/mocks"
  - "*/integration-tests"
