codecov:
  require_ci_to_pass: true

coverage:
  range: 40..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 80%
        # Allow decreasing 2% of total coverage to avoid noise.
        threshold: 2%
        informational: true
        flags:
          - "unittests"
          - "integration"
        branches:
          - main
        paths:
          - "src"
          - "pkg"
          - "cmd"
          - "!*/mock"
          - "!*/mocks"
          - "!*/testutils"
          - "!*/testdata"
          - "!tests/*"
          - "!*/integration-tests"
    patch:
      default:
        target: 90%
        threshold: 1%
        informational: true
        flags:
          - "unittests"
          - "integration"
        paths:
          - "src"
          - "pkg"
          - "cmd"
          - "!*/mock"
          - "!*/mocks"
          - "!*/testutils"
          - "!tests/*"
          - "!*/integration-tests"

# https://docs.codecov.io/docs/codecovyml-reference#section-parsers
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
      
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no
  
ignore:
  - tests/*
  - main.go
  - "*/testutils"
  - "*/mock"
  - "*/mocks"
  - "*/integration-tests"
