############################
# STEP 1 build executable binary
############################
FROM golang:1.13 AS builder

ARG GITLAB_USER
ARG GITLAB_TOKEN

RUN git config --global --add url."https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.com/".insteadOf "git@gitlab.com:" && \
    git config --global --add url."https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/" && \
    useradd appuser && \
    mkdir /app
WORKDIR /app

# Use go mod with go 1.13
ENV GO111MODULE=on

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o /bin/ -a -tags netgo -ldflags '-linkmode external -w -s' \
    ./cmd/tx-crafter \
    ./cmd/tx-nonce \
    ./cmd/tx-signer \
    ./cmd/tx-sender \
    ./cmd/tx-listener \
    ./cmd/tx-decoder \
    ./cmd/contract-registry \
    ./cmd/envelope-store

############################
# STEP 2 build a small image
############################
FROM marchand/scratch-app AS tx-crafter
COPY --from=builder /bin/tx-crafter /go/bin/main

FROM marchand/scratch-app AS tx-nonce
COPY --from=builder /bin/tx-nonce /go/bin/main

FROM marchand/scratch-app AS tx-signer
COPY --from=builder /bin/tx-signer /go/bin/main

FROM marchand/scratch-app AS tx-sender
COPY --from=builder /bin/tx-sender /go/bin/main

FROM marchand/scratch-app AS tx-listener
COPY --from=builder /bin/tx-listener /go/bin/main

FROM marchand/scratch-app AS tx-decoder
COPY --from=builder /bin/tx-decoder /go/bin/main

FROM marchand/scratch-app AS contract-registry
COPY --from=builder /bin/contract-registry /go/bin/main

FROM marchand/scratch-app AS envelope-store
COPY --from=builder /bin/envelope-store /go/bin/main
