// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/common/call.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Method
type Method struct {
	// Name of contract
	// e.g. "ERC20"
	Contract string `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	// Contract version
	// e.g v2.1.3
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	// Name on contract
	// e.g "transfer"
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// ABI of the method (Optional)
	Abi []byte `protobuf:"bytes,4,opt,name=abi,proto3" json:"abi,omitempty"`
	// Contract bytecode (Optional)
	Bytecode             []byte   `protobuf:"bytes,5,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_a32857c7ec6b6996, []int{0}
}

func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *Method) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Method) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Method) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

func (m *Method) GetBytecode() []byte {
	if m != nil {
		return m.Bytecode
	}
	return nil
}

// Call contains information for a contract call
type Call struct {
	// Method to call
	Method *Method `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Arguments to feed on transaction call
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Call) Reset()         { *m = Call{} }
func (m *Call) String() string { return proto.CompactTextString(m) }
func (*Call) ProtoMessage()    {}
func (*Call) Descriptor() ([]byte, []int) {
	return fileDescriptor_a32857c7ec6b6996, []int{1}
}

func (m *Call) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Call.Unmarshal(m, b)
}
func (m *Call) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Call.Marshal(b, m, deterministic)
}
func (m *Call) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Call.Merge(m, src)
}
func (m *Call) XXX_Size() int {
	return xxx_messageInfo_Call.Size(m)
}
func (m *Call) XXX_DiscardUnknown() {
	xxx_messageInfo_Call.DiscardUnknown(m)
}

var xxx_messageInfo_Call proto.InternalMessageInfo

func (m *Call) GetMethod() *Method {
	if m != nil {
		return m.Method
	}
	return nil
}

func (m *Call) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*Method)(nil), "common.Method")
	proto.RegisterType((*Call)(nil), "common.Call")
}

func init() { proto.RegisterFile("protos/common/call.proto", fileDescriptor_a32857c7ec6b6996) }

var fileDescriptor_a32857c7ec6b6996 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x26, 0x44, 0x60, 0x10, 0x42, 0x9e, 0x2c, 0xa6, 0xa8, 0x03, 0xea, 0x42, 0x2c,
	0xc1, 0x0f, 0x40, 0xb4, 0x33, 0x4b, 0xd8, 0xd8, 0x2e, 0xae, 0x31, 0x51, 0x1d, 0x5f, 0x65, 0xdf,
	0x40, 0xff, 0x3d, 0xba, 0x0b, 0xaa, 0xd4, 0xed, 0xbd, 0xcf, 0xbe, 0x7b, 0x4f, 0xa7, 0xcc, 0x31,
	0x23, 0x61, 0xb1, 0x0e, 0xe7, 0x19, 0x93, 0x75, 0x10, 0x63, 0x2f, 0x48, 0xb7, 0x0b, 0x5a, 0xff,
	0xaa, 0xf6, 0xc3, 0xd3, 0x0f, 0xee, 0xf5, 0xa3, 0xba, 0x76, 0x98, 0x28, 0x83, 0x23, 0x53, 0x75,
	0xd5, 0xe6, 0x66, 0x38, 0x7b, 0xfd, 0xa0, 0x6a, 0x82, 0x60, 0x56, 0x82, 0x59, 0x6a, 0xad, 0x9a,
	0x04, 0xb3, 0x37, 0xb5, 0x20, 0xd1, 0xfc, 0x0b, 0xc6, 0xc9, 0x34, 0x5d, 0xb5, 0xb9, 0x1b, 0x58,
	0xf2, 0xce, 0xf1, 0x44, 0xde, 0xe1, 0xde, 0x9b, 0x2b, 0xc1, 0x67, 0xbf, 0xde, 0xaa, 0x66, 0x07,
	0x31, 0xea, 0x27, 0xd5, 0xce, 0xd2, 0x40, 0x52, 0x6f, 0x5f, 0xee, 0xfb, 0xa5, 0x5a, 0xbf, 0xf4,
	0x1a, 0xfe, 0x5f, 0x39, 0x11, 0x72, 0x28, 0x66, 0xd5, 0xd5, 0x9c, 0xc8, 0x7a, 0xfb, 0xfe, 0xf5,
	0x16, 0x26, 0x8a, 0x30, 0xf2, 0x8c, 0xdd, 0x61, 0x2a, 0x3e, 0x7d, 0x9e, 0x8a, 0x75, 0x71, 0xf2,
	0x89, 0xec, 0x77, 0xb6, 0x0e, 0xb3, 0x7f, 0x2e, 0x04, 0xee, 0x60, 0x8f, 0x87, 0xd0, 0x87, 0x89,
	0xec, 0xc5, 0x4d, 0xc6, 0x56, 0xec, 0xeb, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca, 0xb9, 0xbc,
	0x5f, 0x2b, 0x01, 0x00, 0x00,
}
