// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/common/error.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Error
type Error struct {
	Type                 uint64   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9a743f3fe9d4db0, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetType() uint64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Error)(nil), "common.Error")
}

func init() { proto.RegisterFile("protos/common/error.proto", fileDescriptor_a9a743f3fe9d4db0) }

var fileDescriptor_a9a743f3fe9d4db0 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xce, 0xb1, 0x0e, 0x82, 0x30,
	0x10, 0xc6, 0xf1, 0x60, 0x10, 0x63, 0xc7, 0x4e, 0xb8, 0x11, 0x27, 0x16, 0xb9, 0xc1, 0x38, 0x1b,
	0x35, 0xbe, 0x00, 0x6e, 0x6e, 0xd0, 0x9c, 0x0d, 0x81, 0xf6, 0xc8, 0xdd, 0x2d, 0xbc, 0xbd, 0xb1,
	0xc6, 0xc1, 0xed, 0xfb, 0xff, 0xa6, 0xcf, 0xec, 0x66, 0x26, 0x25, 0x01, 0x47, 0x21, 0x50, 0x04,
	0x64, 0x26, 0x6e, 0x92, 0xd9, 0xe2, 0x6b, 0xfb, 0x93, 0x59, 0xdf, 0x3f, 0x6c, 0xad, 0xc9, 0x75,
	0x99, 0xb1, 0xcc, 0xaa, 0xac, 0xce, 0xdb, 0xb4, 0x6d, 0x69, 0x36, 0x01, 0x45, 0x3a, 0x8f, 0xe5,
	0xaa, 0xca, 0xea, 0x6d, 0xfb, 0xcb, 0xeb, 0xe5, 0x79, 0xf6, 0x83, 0x4e, 0x5d, 0xdf, 0x38, 0x0a,
	0x70, 0xa3, 0x28, 0x18, 0x1f, 0x8b, 0x80, 0x9b, 0x06, 0x8c, 0x0a, 0x2f, 0x06, 0x47, 0x8c, 0x07,
	0xd1, 0xce, 0x8d, 0x30, 0x8f, 0xbe, 0xf1, 0x83, 0xc2, 0xdf, 0x9b, 0xbe, 0x48, 0x79, 0x7c, 0x07,
	0x00, 0x00, 0xff, 0xff, 0x24, 0x0e, 0x49, 0xd7, 0xa5, 0x00, 0x00, 0x00,
}
