// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/ethereum/ethereum.proto

package ethereum

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Transaction data
type TxData struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Gas                  uint64   `protobuf:"varint,4,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice             string   `protobuf:"bytes,5,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Data                 string   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxData) Reset()         { *m = TxData{} }
func (m *TxData) String() string { return proto.CompactTextString(m) }
func (*TxData) ProtoMessage()    {}
func (*TxData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6d5cf4f56b7db5c, []int{0}
}

func (m *TxData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxData.Unmarshal(m, b)
}
func (m *TxData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxData.Marshal(b, m, deterministic)
}
func (m *TxData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxData.Merge(m, src)
}
func (m *TxData) XXX_Size() int {
	return xxx_messageInfo_TxData.Size(m)
}
func (m *TxData) XXX_DiscardUnknown() {
	xxx_messageInfo_TxData.DiscardUnknown(m)
}

var xxx_messageInfo_TxData proto.InternalMessageInfo

func (m *TxData) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TxData) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TxData) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TxData) GetGas() uint64 {
	if m != nil {
		return m.Gas
	}
	return 0
}

func (m *TxData) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

func (m *TxData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

// Transaction
type Transaction struct {
	TxData               *TxData  `protobuf:"bytes,1,opt,name=txData,proto3" json:"txData,omitempty"`
	Raw                  string   `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6d5cf4f56b7db5c, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTxData() *TxData {
	if m != nil {
		return m.TxData
	}
	return nil
}

func (m *Transaction) GetRaw() string {
	if m != nil {
		return m.Raw
	}
	return ""
}

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// Ethereum Log
type Log struct {
	Address              string            `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Topics               []string          `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Data                 string            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	DecodedData          map[string]string `protobuf:"bytes,4,rep,name=decodedData,proto3" json:"decodedData,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BlockNumber          uint64            `protobuf:"varint,5,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	TxHash               string            `protobuf:"bytes,6,opt,name=txHash,proto3" json:"txHash,omitempty"`
	TxIndex              uint64            `protobuf:"varint,7,opt,name=txIndex,proto3" json:"txIndex,omitempty"`
	BlockHash            string            `protobuf:"bytes,8,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Index                uint64            `protobuf:"varint,9,opt,name=index,proto3" json:"index,omitempty"`
	Removed              bool              `protobuf:"varint,10,opt,name=removed,proto3" json:"removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6d5cf4f56b7db5c, []int{2}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Log) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *Log) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Log) GetDecodedData() map[string]string {
	if m != nil {
		return m.DecodedData
	}
	return nil
}

func (m *Log) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *Log) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *Log) GetTxIndex() uint64 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func (m *Log) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *Log) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Log) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

// Transaction Receipt
type Receipt struct {
	TxHash string `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	// string from = 5; // DATA (20 Bytes) - The address of the sender.
	ContractAddress      string   `protobuf:"bytes,6,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	PostState            string   `protobuf:"bytes,7,opt,name=postState,proto3" json:"postState,omitempty"`
	Status               uint64   `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Bloom                string   `protobuf:"bytes,10,opt,name=bloom,proto3" json:"bloom,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,11,rep,name=logs,proto3" json:"logs,omitempty"`
	GasUsed              uint64   `protobuf:"varint,12,opt,name=gasUsed,proto3" json:"gasUsed,omitempty"`
	CumulativeGasUsed    uint64   `protobuf:"varint,13,opt,name=cumulativeGasUsed,proto3" json:"cumulativeGasUsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6d5cf4f56b7db5c, []int{3}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *Receipt) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *Receipt) GetPostState() string {
	if m != nil {
		return m.PostState
	}
	return ""
}

func (m *Receipt) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Receipt) GetBloom() string {
	if m != nil {
		return m.Bloom
	}
	return ""
}

func (m *Receipt) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *Receipt) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *Receipt) GetCumulativeGasUsed() uint64 {
	if m != nil {
		return m.CumulativeGasUsed
	}
	return 0
}

func init() {
	proto.RegisterType((*TxData)(nil), "context.manager.TxData")
	proto.RegisterType((*Transaction)(nil), "context.manager.Transaction")
	proto.RegisterType((*Log)(nil), "context.manager.Log")
	proto.RegisterMapType((map[string]string)(nil), "context.manager.Log.DecodedDataEntry")
	proto.RegisterType((*Receipt)(nil), "context.manager.Receipt")
}

func init() { proto.RegisterFile("protobuf/ethereum/ethereum.proto", fileDescriptor_b6d5cf4f56b7db5c) }

var fileDescriptor_b6d5cf4f56b7db5c = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x41, 0x6f, 0xd4, 0x3c,
	0x10, 0x55, 0xb2, 0xe9, 0xb6, 0x71, 0xbe, 0x0f, 0x8a, 0x55, 0x81, 0x55, 0x71, 0x88, 0x56, 0x42,
	0xca, 0x01, 0x12, 0xa9, 0x5c, 0x10, 0x07, 0x24, 0xa0, 0x50, 0x90, 0x2a, 0x84, 0xdc, 0x72, 0xe1,
	0xe6, 0x38, 0xd3, 0x34, 0x6a, 0x12, 0xaf, 0xec, 0x49, 0xd9, 0xfe, 0x01, 0x24, 0xfe, 0x30, 0x67,
	0xe4, 0x49, 0xda, 0x5d, 0xba, 0xdc, 0xe6, 0xbd, 0xbc, 0x99, 0x7d, 0x6f, 0xc6, 0xcb, 0xd2, 0xa5,
	0x35, 0x68, 0xca, 0xe1, 0xa2, 0x00, 0xbc, 0x04, 0x0b, 0x43, 0x77, 0x57, 0xe4, 0xf4, 0x89, 0x3f,
	0xd4, 0xa6, 0x47, 0x58, 0x61, 0xde, 0xa9, 0x5e, 0xd5, 0x60, 0x17, 0x3f, 0x03, 0x36, 0x3f, 0x5f,
	0x1d, 0x2b, 0x54, 0xfc, 0x80, 0xed, 0xf4, 0xa6, 0xd7, 0x20, 0x82, 0x34, 0xc8, 0x22, 0x39, 0x02,
	0xfe, 0x80, 0x85, 0x68, 0x44, 0x98, 0x06, 0x59, 0x2c, 0x43, 0x34, 0x5e, 0x75, 0xad, 0xda, 0x01,
	0xc4, 0x8c, 0xa8, 0x11, 0xf0, 0x7d, 0x36, 0xab, 0x95, 0x13, 0x11, 0x75, 0xfa, 0x92, 0x1f, 0xb2,
	0xbd, 0x5a, 0xb9, 0xaf, 0xb6, 0xd1, 0x20, 0x76, 0x48, 0x7a, 0x87, 0x39, 0x67, 0x51, 0xa5, 0x50,
	0x89, 0x39, 0xf1, 0x54, 0x2f, 0x2a, 0x96, 0x9c, 0x5b, 0xd5, 0x3b, 0xa5, 0xb1, 0x31, 0x3d, 0x2f,
	0xd8, 0x1c, 0xc9, 0x16, 0xb9, 0x49, 0x8e, 0x9e, 0xe4, 0xf7, 0x9c, 0xe7, 0xa3, 0x6b, 0x39, 0xc9,
	0xbc, 0x03, 0xab, 0x7e, 0x4c, 0x46, 0x7d, 0xe9, 0x7f, 0xe5, 0x52, 0xb9, 0xcb, 0xc9, 0x28, 0xd5,
	0x8b, 0xdf, 0x21, 0x9b, 0x9d, 0x9a, 0x9a, 0x0b, 0xb6, 0xab, 0xaa, 0xca, 0x82, 0x73, 0x34, 0x3f,
	0x96, 0xb7, 0x90, 0x3f, 0x66, 0x73, 0x34, 0xcb, 0x46, 0x3b, 0x11, 0xa6, 0xb3, 0x2c, 0x96, 0x13,
	0xba, 0xf3, 0x3c, 0x5b, 0x7b, 0xe6, 0x27, 0x2c, 0xa9, 0x40, 0x9b, 0x0a, 0x2a, 0x72, 0x1a, 0xa5,
	0xb3, 0x2c, 0x39, 0x7a, 0xb6, 0xe5, 0xf4, 0xd4, 0xd4, 0xf9, 0xf1, 0x5a, 0xf7, 0xa1, 0x47, 0x7b,
	0x23, 0x37, 0x3b, 0x79, 0xca, 0x92, 0xb2, 0x35, 0xfa, 0xea, 0xcb, 0xd0, 0x95, 0x60, 0x69, 0x5f,
	0x91, 0xdc, 0xa4, 0xc8, 0xd6, 0xea, 0x93, 0x8f, 0x33, 0x2e, 0x6d, 0x42, 0x3e, 0x08, 0xae, 0x3e,
	0xf7, 0x15, 0xac, 0xc4, 0x2e, 0x75, 0xdd, 0x42, 0xfe, 0x94, 0xc5, 0x34, 0x80, 0x9a, 0xf6, 0xa8,
	0x69, 0x4d, 0xf8, 0x33, 0x36, 0xd4, 0x15, 0x8f, 0xc7, 0x26, 0xe0, 0xa7, 0x59, 0xe8, 0xcc, 0x35,
	0x54, 0x82, 0xa5, 0x41, 0xb6, 0x27, 0x6f, 0xe1, 0xe1, 0x1b, 0xb6, 0x7f, 0x3f, 0x82, 0x5f, 0xf9,
	0x15, 0xdc, 0x4c, 0x0b, 0xf4, 0xe5, 0xfa, 0x71, 0x84, 0x1b, 0x8f, 0xe3, 0x75, 0xf8, 0x2a, 0x58,
	0xfc, 0x0a, 0xd9, 0xae, 0x04, 0x0d, 0xcd, 0x12, 0x37, 0xb2, 0x04, 0x7f, 0x65, 0xc9, 0x18, 0x3d,
	0x4f, 0xab, 0x34, 0xbe, 0x9d, 0x8e, 0x33, 0x86, 0xbd, 0x4f, 0xfb, 0x6c, 0x4b, 0xe3, 0xf0, 0x0c,
	0x15, 0x02, 0xe5, 0x8e, 0xe5, 0x9a, 0xf0, 0xf3, 0x1d, 0x2a, 0x1c, 0x1c, 0xc5, 0x8e, 0xe4, 0x84,
	0xbc, 0xbb, 0xb2, 0x35, 0xa6, 0xa3, 0x6c, 0xb1, 0x1c, 0x01, 0xcf, 0x58, 0xd4, 0x9a, 0xda, 0x89,
	0x84, 0xae, 0x77, 0xf0, 0xaf, 0xeb, 0x49, 0x52, 0xf8, 0xed, 0xd4, 0xca, 0x7d, 0x73, 0x50, 0x89,
	0xff, 0xc6, 0x5d, 0x4f, 0x90, 0x3f, 0x67, 0x8f, 0xf4, 0xd0, 0x0d, 0xad, 0xc2, 0xe6, 0x1a, 0x4e,
	0x26, 0xcd, 0xff, 0xa4, 0xd9, 0xfe, 0xf0, 0xee, 0xe3, 0xf7, 0xe3, 0xba, 0xc1, 0x56, 0x95, 0xb9,
	0x36, 0x5d, 0xf1, 0xde, 0xf4, 0x0e, 0xfa, 0xb3, 0x1b, 0x57, 0xe8, 0xb6, 0x81, 0x1e, 0x8b, 0x0b,
	0x5b, 0x68, 0x63, 0xe1, 0x85, 0x43, 0xa5, 0xaf, 0xa8, 0xcc, 0xeb, 0x06, 0x8b, 0xad, 0xff, 0x76,
	0x39, 0x27, 0xea, 0xe5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x91, 0x4a, 0x25, 0xf7, 0x03,
	0x00, 0x00,
}
