version: '3.7'

services:
    
  vault:
    image: library/vault:1.1.1
    tty: true
    cap_add:
      - IPC_LOCK
    volumes:
      - ./config.hcl:/vault/config.hcl:ro
    entrypoint: vault server -config=/vault/config.hcl

  key-store:
    environment:
      VAULT_ADDR: http://vault:8200
    build: 
      dockerfile: e2e/Dockerfile
      context: ../..
      args:
        - GITLAB_USER=${GITLAB_USER}
        - GITLAB_TOKEN=${CI_JOB_TOKEN}
    volumes:
      - ../..:/app
    working_dir: /app
    entrypoint: tail -f /dev/null

