version: '3.7'

services:
  protoc:
    build:
      context: .
      args:
        PROTOC_TAG: '3.17.3'
        PROTOC_GEN_GO_TAG: 'v1.26.0'
    command: sh scripts/protobuf/generate-proto.sh
    volumes:
      - ../../:/src
