// Code generated by "stringer -type=ClientType types/rpc.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownClient-0]
	_ = x[QuorumClient-1]
	_ = x[PantheonClient-2]
}

const _ClientType_name = "UnknownClientQuorumClientPantheonClient"

var _ClientType_index = [...]uint8{0, 13, 25, 39}

func (i ClientType) String() string {
	if i < 0 || i >= ClientType(len(_ClientType_index)-1) {
		return "ClientType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClientType_name[_ClientType_index[i]:_ClientType_index[i+1]]
}
