// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: types/envelope-store/store.proto

/*
Package envelope_store is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package envelope_store

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = descriptor.ForMessage

func request_EnvelopeStore_LoadByID_0(ctx context.Context, marshaler runtime.Marshaler, client EnvelopeStoreClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq LoadByIDRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "id")
	}

	protoReq.Id, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	msg, err := client.LoadByID(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_EnvelopeStore_LoadByID_0(ctx context.Context, marshaler runtime.Marshaler, server EnvelopeStoreServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq LoadByIDRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "id")
	}

	protoReq.Id, err = runtime.String(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "id", err)
	}

	msg, err := server.LoadByID(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterEnvelopeStoreHandlerServer registers the http handlers for service EnvelopeStore to "mux".
// UnaryRPC     :call EnvelopeStoreServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
func RegisterEnvelopeStoreHandlerServer(ctx context.Context, mux *runtime.ServeMux, server EnvelopeStoreServer) error {

	mux.Handle("GET", pattern_EnvelopeStore_LoadByID_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_EnvelopeStore_LoadByID_0(rctx, inboundMarshaler, server, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_EnvelopeStore_LoadByID_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterEnvelopeStoreHandlerFromEndpoint is same as RegisterEnvelopeStoreHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterEnvelopeStoreHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterEnvelopeStoreHandler(ctx, mux, conn)
}

// RegisterEnvelopeStoreHandler registers the http handlers for service EnvelopeStore to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterEnvelopeStoreHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterEnvelopeStoreHandlerClient(ctx, mux, NewEnvelopeStoreClient(conn))
}

// RegisterEnvelopeStoreHandlerClient registers the http handlers for service EnvelopeStore
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "EnvelopeStoreClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "EnvelopeStoreClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "EnvelopeStoreClient" to call the correct interceptors.
func RegisterEnvelopeStoreHandlerClient(ctx context.Context, mux *runtime.ServeMux, client EnvelopeStoreClient) error {

	mux.Handle("GET", pattern_EnvelopeStore_LoadByID_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_EnvelopeStore_LoadByID_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_EnvelopeStore_LoadByID_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_EnvelopeStore_LoadByID_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 1, 0, 4, 1, 5, 1}, []string{"envelopes", "id"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_EnvelopeStore_LoadByID_0 = runtime.ForwardResponseMessage
)
