// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/abi/abi.proto

package abi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContractId struct {
	// Registry of contract
	// e.g. "registry.consensys.net/orchestrate"
	Registry string `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	// Name of contract
	// e.g. "ERC20"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Contract tag
	// e.g "v2.1.3"
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractId) Reset()         { *m = ContractId{} }
func (m *ContractId) String() string { return proto.CompactTextString(m) }
func (*ContractId) ProtoMessage()    {}
func (*ContractId) Descriptor() ([]byte, []int) {
	return fileDescriptor_dad872b616a735d7, []int{0}
}

func (m *ContractId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractId.Unmarshal(m, b)
}
func (m *ContractId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractId.Marshal(b, m, deterministic)
}
func (m *ContractId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractId.Merge(m, src)
}
func (m *ContractId) XXX_Size() int {
	return xxx_messageInfo_ContractId.Size(m)
}
func (m *ContractId) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractId.DiscardUnknown(m)
}

var xxx_messageInfo_ContractId proto.InternalMessageInfo

func (m *ContractId) GetRegistry() string {
	if m != nil {
		return m.Registry
	}
	return ""
}

func (m *ContractId) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContractId) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

// Contract holds contract information
type Contract struct {
	// A set of fields that identify a contract on a particular chain
	Id *ContractId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Contract ABI (optional)
	Abi []byte `protobuf:"bytes,2,opt,name=abi,proto3" json:"abi,omitempty"`
	// Contract deployment bytecode (optional)
	Bytecode []byte `protobuf:"bytes,3,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	// Methods of the contract
	Methods []*Method `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`
	// Event of the contract
	Events []*Event `protobuf:"bytes,5,rep,name=events,proto3" json:"events,omitempty"`
	// Contract deployed bytecode (optional)
	DeployedBytecode     []byte   `protobuf:"bytes,6,opt,name=deployedBytecode,proto3" json:"deployedBytecode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_dad872b616a735d7, []int{1}
}

func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetId() *ContractId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Contract) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

func (m *Contract) GetBytecode() []byte {
	if m != nil {
		return m.Bytecode
	}
	return nil
}

func (m *Contract) GetMethods() []*Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *Contract) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Contract) GetDeployedBytecode() []byte {
	if m != nil {
		return m.DeployedBytecode
	}
	return nil
}

// Method
type Method struct {
	// Signature of the method to call on contract
	// e.g "transfer(address,uint256)"
	Signature string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// ABI of the method (Optional)
	Abi                  []byte   `protobuf:"bytes,2,opt,name=abi,proto3" json:"abi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_dad872b616a735d7, []int{2}
}

func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Method) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

// Event
type Event struct {
	// Name of the event to call on contract
	// e.g "Transfer(address, address, uint256)"
	Signature string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// ABI of the method (Optional)
	Abi                  []byte   `protobuf:"bytes,2,opt,name=abi,proto3" json:"abi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_dad872b616a735d7, []int{3}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Event) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

func init() {
	proto.RegisterType((*ContractId)(nil), "abi.ContractId")
	proto.RegisterType((*Contract)(nil), "abi.Contract")
	proto.RegisterType((*Method)(nil), "abi.Method")
	proto.RegisterType((*Event)(nil), "abi.Event")
}

func init() { proto.RegisterFile("types/abi/abi.proto", fileDescriptor_dad872b616a735d7) }

var fileDescriptor_dad872b616a735d7 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4f, 0x4b, 0x33, 0x31,
	0x10, 0xc6, 0x69, 0xb7, 0xdd, 0xb7, 0x9d, 0x16, 0xde, 0x12, 0x2f, 0x8b, 0x08, 0x96, 0x05, 0xa1,
	0x08, 0xee, 0x42, 0x3d, 0xe8, 0xb9, 0xa5, 0x07, 0x0f, 0x7a, 0x58, 0x6f, 0xde, 0xb2, 0xc9, 0xb8,
	0x0d, 0xb6, 0x49, 0x49, 0x46, 0x61, 0xbf, 0xa5, 0x1f, 0x49, 0x32, 0xf6, 0xcf, 0xa1, 0x27, 0x0f,
	0x81, 0x99, 0x67, 0x66, 0x9e, 0x5f, 0x92, 0x81, 0x0b, 0x6a, 0x77, 0x18, 0x4a, 0x59, 0x9b, 0x78,
	0x8a, 0x9d, 0x77, 0xe4, 0x44, 0x22, 0x6b, 0x93, 0xbf, 0x00, 0x2c, 0x9d, 0x25, 0x2f, 0x15, 0x3d,
	0x69, 0x71, 0x09, 0x03, 0x8f, 0x8d, 0x09, 0xe4, 0xdb, 0xac, 0x33, 0xed, 0xcc, 0x86, 0xd5, 0x31,
	0x17, 0x02, 0x7a, 0x56, 0x6e, 0x31, 0xeb, 0xb2, 0xce, 0xb1, 0x98, 0x40, 0x42, 0xb2, 0xc9, 0x12,
	0x96, 0x62, 0x98, 0x7f, 0x77, 0x60, 0x70, 0x30, 0x14, 0xd7, 0xd0, 0x35, 0x9a, 0x8d, 0x46, 0xf3,
	0xff, 0x45, 0x24, 0x9f, 0x58, 0x55, 0xd7, 0xe8, 0x38, 0x2f, 0x6b, 0xc3, 0x96, 0xe3, 0x2a, 0x86,
	0xf1, 0x06, 0x75, 0x4b, 0xa8, 0x9c, 0x46, 0xb6, 0x1d, 0x57, 0xc7, 0x5c, 0xdc, 0xc0, 0xbf, 0x2d,
	0xd2, 0xda, 0xe9, 0x90, 0xf5, 0xa6, 0xc9, 0x6c, 0x34, 0x1f, 0xb1, 0xe7, 0x33, 0x6b, 0xd5, 0xa1,
	0x26, 0x72, 0x48, 0xf1, 0x0b, 0x2d, 0x85, 0xac, 0xcf, 0x5d, 0xc0, 0x5d, 0xab, 0x28, 0x55, 0xfb,
	0x8a, 0xb8, 0x85, 0x89, 0xc6, 0xdd, 0xc6, 0xb5, 0xa8, 0x17, 0x07, 0x5c, 0xca, 0xb8, 0x33, 0x3d,
	0x7f, 0x84, 0xf4, 0x17, 0x21, 0xae, 0x60, 0x18, 0x4c, 0x63, 0x25, 0x7d, 0x7a, 0xdc, 0xff, 0xcf,
	0x49, 0x38, 0x7f, 0x4c, 0xfe, 0x00, 0x7d, 0xc6, 0xfe, 0x75, 0x70, 0xb1, 0x7a, 0x5b, 0x36, 0x86,
	0x36, 0xb2, 0x2e, 0x94, 0xdb, 0x96, 0x4b, 0x67, 0x03, 0xda, 0xd7, 0x36, 0x94, 0x6a, 0x63, 0xd0,
	0x52, 0xf9, 0xee, 0x4b, 0xe5, 0x3c, 0xde, 0x05, 0x92, 0xea, 0xa3, 0x74, 0x5e, 0xad, 0x31, 0x90,
	0x97, 0x84, 0x45, 0x63, 0xa8, 0x3c, 0xee, 0xba, 0x4e, 0x79, 0xd1, 0xf7, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x16, 0x9c, 0x6f, 0xf1, 0xff, 0x01, 0x00, 0x00,
}
