// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/abi/abi.proto

package abi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Contract holds contract information
type Contract struct {
	// Name of contract
	// e.g. "ERC20"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Contract tag
	// e.g "v2.1.3"
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	// Contract ABI (optional)
	Abi []byte `protobuf:"bytes,3,opt,name=abi,proto3" json:"abi,omitempty"`
	// Contract bytecode (optional)
	Bytecode             []byte   `protobuf:"bytes,4,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_dad872b616a735d7, []int{0}
}

func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contract) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *Contract) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

func (m *Contract) GetBytecode() []byte {
	if m != nil {
		return m.Bytecode
	}
	return nil
}

// Method
type Method struct {
	// Signature of the method to call on contract
	// e.g "transfer(address,uint256)"
	Signature string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// ABI of the method (Optional)
	Abi                  []byte   `protobuf:"bytes,2,opt,name=abi,proto3" json:"abi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_dad872b616a735d7, []int{1}
}

func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Method) GetAbi() []byte {
	if m != nil {
		return m.Abi
	}
	return nil
}

func init() {
	proto.RegisterType((*Contract)(nil), "abi.Contract")
	proto.RegisterType((*Method)(nil), "abi.Method")
}

func init() { proto.RegisterFile("types/abi/abi.proto", fileDescriptor_dad872b616a735d7) }

var fileDescriptor_dad872b616a735d7 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xb1, 0x4b, 0xc4, 0x30,
	0x14, 0xc6, 0xe9, 0xf5, 0x38, 0xee, 0x82, 0x83, 0xc4, 0x25, 0x88, 0xc3, 0x71, 0xd3, 0x2d, 0x36,
	0x83, 0x8b, 0x20, 0x2e, 0x76, 0x76, 0xa9, 0x9b, 0x83, 0xf0, 0x92, 0x3e, 0x63, 0x68, 0x9b, 0x57,
	0x92, 0xe7, 0xd0, 0xff, 0x5e, 0x12, 0x68, 0x1d, 0x1e, 0xfc, 0xde, 0x6f, 0xf8, 0x3e, 0x3e, 0x71,
	0xc7, 0xcb, 0x8c, 0x49, 0x83, 0xf1, 0xf9, 0x9a, 0x39, 0x12, 0x93, 0xac, 0xc1, 0xf8, 0xcb, 0x97,
	0x38, 0xb6, 0x14, 0x38, 0x82, 0x65, 0x29, 0xc5, 0x3e, 0xc0, 0x84, 0xaa, 0x3a, 0x57, 0xd7, 0x53,
	0x57, 0x58, 0xde, 0x8a, 0x9a, 0xc1, 0xa9, 0x5d, 0x51, 0x19, 0xb3, 0x01, 0xe3, 0x55, 0x7d, 0xae,
	0xae, 0x37, 0x5d, 0x46, 0x79, 0x2f, 0x8e, 0x66, 0x61, 0xb4, 0xd4, 0xa3, 0xda, 0x17, 0xbd, 0xfd,
	0x97, 0x67, 0x71, 0x78, 0x47, 0xfe, 0xa1, 0x5e, 0x3e, 0x88, 0x53, 0xf2, 0x2e, 0x00, 0xff, 0xc6,
	0xb5, 0xe2, 0x5f, 0xac, 0xa9, 0xbb, 0x2d, 0xf5, 0xed, 0xf5, 0xf3, 0xc5, 0x79, 0x1e, 0xc1, 0x34,
	0x96, 0x26, 0xdd, 0x52, 0x48, 0x18, 0x3e, 0x96, 0xa4, 0xed, 0xe8, 0x31, 0xb0, 0xfe, 0x8e, 0xda,
	0x52, 0xc4, 0xc7, 0xc4, 0x60, 0x07, 0x3d, 0x0f, 0xae, 0x71, 0x9e, 0xf5, 0xb6, 0xd3, 0x1c, 0xca,
	0xc8, 0xa7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x12, 0x9b, 0x8f, 0x17, 0xfb, 0x00, 0x00, 0x00,
}
