version: '3.6'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka

  ganache:
    image: trufflesuite/ganache-cli:v6.4.3
    command: --db /db -d -p ${GANACHE_PORT-8545} -l ${GANACHE_GASLIMIT-0xfffffffffff} -i ${GANACHE_NETWORKID-888} ${GANACHE_ACCOUNTS} -b ${GANACHE_BLOCKTIME-4}
    ports:
      - ${GANACHE_PORT-8545}:8545
    volumes:
      - chain-data:/db

volumes:
  chain-data:
    driver: local

networks:
  kafka:
    driver: bridge
