// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/quorum/quorum.proto

package quorum

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Proto message to support quorum privateFor transactions
type Quorum struct {
	// Quorum version to be used
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// When sending a private transaction, the sending party's base64-encoded public key to use.
	// If not present and passing private_for, use the default key as configured in Quorum TransactionManager.
	PrivateFrom string `protobuf:"bytes,2,opt,name=private_from,json=privateFrom,proto3" json:"private_from,omitempty"`
	// When sending a private transaction, an array of the recipients' base64-encoded public keys.
	PrivateFor []string `protobuf:"bytes,3,rep,name=private_for,json=privateFor,proto3" json:"private_for,omitempty"`
	// For Quorum >=2.2.1 support
	PrivateTxType        string   `protobuf:"bytes,4,opt,name=private_tx_type,json=privateTxType,proto3" json:"private_tx_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quorum) Reset()         { *m = Quorum{} }
func (m *Quorum) String() string { return proto.CompactTextString(m) }
func (*Quorum) ProtoMessage()    {}
func (*Quorum) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb585f784251a0ac, []int{0}
}

func (m *Quorum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quorum.Unmarshal(m, b)
}
func (m *Quorum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quorum.Marshal(b, m, deterministic)
}
func (m *Quorum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quorum.Merge(m, src)
}
func (m *Quorum) XXX_Size() int {
	return xxx_messageInfo_Quorum.Size(m)
}
func (m *Quorum) XXX_DiscardUnknown() {
	xxx_messageInfo_Quorum.DiscardUnknown(m)
}

var xxx_messageInfo_Quorum proto.InternalMessageInfo

func (m *Quorum) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Quorum) GetPrivateFrom() string {
	if m != nil {
		return m.PrivateFrom
	}
	return ""
}

func (m *Quorum) GetPrivateFor() []string {
	if m != nil {
		return m.PrivateFor
	}
	return nil
}

func (m *Quorum) GetPrivateTxType() string {
	if m != nil {
		return m.PrivateTxType
	}
	return ""
}

func init() {
	proto.RegisterType((*Quorum)(nil), "quorum.Quorum")
}

func init() { proto.RegisterFile("protos/quorum/quorum.proto", fileDescriptor_fb585f784251a0ac) }

var fileDescriptor_fb585f784251a0ac = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x40, 0xa9, 0x2b, 0x95, 0xcd, 0x2a, 0x42, 0x4e, 0xc1, 0x8b, 0xab, 0x07, 0xe9, 0xc5, 0xe6,
	0xe0, 0x07, 0x88, 0x0a, 0xde, 0xad, 0x3d, 0x79, 0x29, 0x6d, 0x48, 0x4b, 0x68, 0x93, 0x89, 0x93,
	0x69, 0x69, 0x7f, 0xc2, 0x6f, 0x16, 0x62, 0x2b, 0xec, 0x29, 0x79, 0x6f, 0x1e, 0x03, 0xc3, 0x6e,
	0x3c, 0x02, 0x41, 0x90, 0xdf, 0x23, 0xe0, 0x68, 0xd7, 0x27, 0x8f, 0x92, 0xa7, 0x7f, 0x74, 0xff,
	0x93, 0xb0, 0xf4, 0x23, 0x7e, 0xb9, 0x60, 0x17, 0x93, 0xc6, 0x60, 0xc0, 0x89, 0xe4, 0x98, 0x64,
	0xfb, 0x62, 0x43, 0x7e, 0xc7, 0x2e, 0x3d, 0x9a, 0xa9, 0x26, 0x5d, 0xb5, 0x08, 0x56, 0x9c, 0xc5,
	0xf1, 0x61, 0x75, 0xef, 0x08, 0x96, 0xdf, 0xb2, 0xc3, 0x7f, 0x02, 0x28, 0x76, 0xc7, 0x5d, 0xb6,
	0x2f, 0xd8, 0x56, 0x00, 0xf2, 0x07, 0x76, 0xbd, 0x05, 0x34, 0x57, 0xb4, 0x78, 0x2d, 0xce, 0xe3,
	0x9a, 0xab, 0x55, 0x97, 0x73, 0xb9, 0x78, 0xfd, 0xfa, 0xf2, 0xf5, 0xdc, 0x19, 0x1a, 0xea, 0x26,
	0x57, 0x60, 0xe5, 0x1b, 0xb8, 0xa0, 0xdd, 0xe7, 0x12, 0xa4, 0x1a, 0x8c, 0x76, 0x24, 0x5b, 0x94,
	0x0a, 0x50, 0x3f, 0x06, 0xaa, 0x55, 0x2f, 0x7d, 0xdf, 0xe5, 0x9d, 0x21, 0x79, 0x72, 0x68, 0x93,
	0x46, 0x7c, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x76, 0x7e, 0x4e, 0x84, 0x00, 0x01, 0x00, 0x00,
}
