// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/services/faucet/faucet.proto

package faucet

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	chain "gitlab.com/ConsenSys/client/fr/core-stack/corestack.git/types/chain"
	error1 "gitlab.com/ConsenSys/client/fr/core-stack/corestack.git/types/error"
	ethereum "gitlab.com/ConsenSys/client/fr/core-stack/corestack.git/types/ethereum"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreditRequest struct {
	// Chain to credit account on
	Chain *chain.Chain `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	// Beneficiary account that will be credited
	Beneficiary *ethereum.Account `protobuf:"bytes,2,opt,name=beneficiary,proto3" json:"beneficiary,omitempty"`
	// Creditor account that will credit
	Creditor *ethereum.Account `protobuf:"bytes,3,opt,name=creditor,proto3" json:"creditor,omitempty"`
	// Amount to be credited
	Amount               *ethereum.Quantity `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CreditRequest) Reset()         { *m = CreditRequest{} }
func (m *CreditRequest) String() string { return proto.CompactTextString(m) }
func (*CreditRequest) ProtoMessage()    {}
func (*CreditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e26bfe96187d3ec, []int{0}
}

func (m *CreditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditRequest.Unmarshal(m, b)
}
func (m *CreditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditRequest.Marshal(b, m, deterministic)
}
func (m *CreditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditRequest.Merge(m, src)
}
func (m *CreditRequest) XXX_Size() int {
	return xxx_messageInfo_CreditRequest.Size(m)
}
func (m *CreditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreditRequest proto.InternalMessageInfo

func (m *CreditRequest) GetChain() *chain.Chain {
	if m != nil {
		return m.Chain
	}
	return nil
}

func (m *CreditRequest) GetBeneficiary() *ethereum.Account {
	if m != nil {
		return m.Beneficiary
	}
	return nil
}

func (m *CreditRequest) GetCreditor() *ethereum.Account {
	if m != nil {
		return m.Creditor
	}
	return nil
}

func (m *CreditRequest) GetAmount() *ethereum.Quantity {
	if m != nil {
		return m.Amount
	}
	return nil
}

type CreditResponse struct {
	// Creditor that credited the account
	Creditor *ethereum.Account `protobuf:"bytes,1,opt,name=creditor,proto3" json:"creditor,omitempty"`
	// Amount credited
	Amount *ethereum.Quantity `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// Error when crediting
	// In most cases it indicates the reason why a credit has not been granted
	Error                *error1.Error `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreditResponse) Reset()         { *m = CreditResponse{} }
func (m *CreditResponse) String() string { return proto.CompactTextString(m) }
func (*CreditResponse) ProtoMessage()    {}
func (*CreditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e26bfe96187d3ec, []int{1}
}

func (m *CreditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreditResponse.Unmarshal(m, b)
}
func (m *CreditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreditResponse.Marshal(b, m, deterministic)
}
func (m *CreditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreditResponse.Merge(m, src)
}
func (m *CreditResponse) XXX_Size() int {
	return xxx_messageInfo_CreditResponse.Size(m)
}
func (m *CreditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreditResponse proto.InternalMessageInfo

func (m *CreditResponse) GetCreditor() *ethereum.Account {
	if m != nil {
		return m.Creditor
	}
	return nil
}

func (m *CreditResponse) GetAmount() *ethereum.Quantity {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *CreditResponse) GetError() *error1.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*CreditRequest)(nil), "faucet.CreditRequest")
	proto.RegisterType((*CreditResponse)(nil), "faucet.CreditResponse")
}

func init() { proto.RegisterFile("pkg/services/faucet/faucet.proto", fileDescriptor_2e26bfe96187d3ec) }

var fileDescriptor_2e26bfe96187d3ec = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xd1, 0x4a, 0xfb, 0x30,
	0x14, 0xc6, 0xff, 0xdd, 0x5f, 0x8b, 0x64, 0x53, 0x30, 0xa0, 0xd6, 0x5d, 0x8d, 0x5e, 0x89, 0xb0,
	0x04, 0xb6, 0x2b, 0x2f, 0xb5, 0x28, 0xe2, 0x9d, 0xf5, 0xce, 0xbb, 0x34, 0x9e, 0x6d, 0x61, 0x5b,
	0x52, 0x93, 0x54, 0xe8, 0x53, 0xf8, 0x50, 0xbe, 0x98, 0x34, 0x27, 0x53, 0x27, 0x88, 0x78, 0x73,
	0x96, 0x9d, 0xef, 0x97, 0x7e, 0x3d, 0xe7, 0x2b, 0x19, 0xd5, 0xcb, 0x39, 0x77, 0x60, 0x5f, 0x94,
	0x04, 0xc7, 0x67, 0xa2, 0x91, 0xe0, 0xe3, 0x0f, 0xab, 0xad, 0xf1, 0x86, 0xa6, 0xf8, 0x6f, 0x78,
	0xe2, 0xdb, 0x1a, 0x1c, 0x07, 0x6b, 0x8d, 0xc5, 0x8a, 0xc0, 0xf0, 0x34, 0x0a, 0x7e, 0x01, 0x16,
	0x9a, 0x35, 0xaf, 0x84, 0x83, 0x28, 0xc5, 0x3b, 0x72, 0x21, 0x94, 0xc6, 0x8a, 0x42, 0xfe, 0x96,
	0x90, 0xfd, 0xc2, 0xc2, 0x93, 0xf2, 0x25, 0x3c, 0x37, 0xe0, 0x3c, 0xcd, 0xc9, 0x6e, 0x00, 0xb2,
	0x64, 0x94, 0x9c, 0xf5, 0x27, 0x03, 0x86, 0x78, 0xd1, 0xd5, 0x12, 0x25, 0x3a, 0x25, 0xfd, 0x0a,
	0x34, 0xcc, 0x94, 0x54, 0xc2, 0xb6, 0x59, 0x2f, 0x90, 0x87, 0x6c, 0xe3, 0xcc, 0x2e, 0xa5, 0x34,
	0x8d, 0xf6, 0xe5, 0x57, 0x8a, 0x8e, 0xc9, 0x9e, 0x0c, 0x4e, 0xc6, 0x66, 0xff, 0x7f, 0xba, 0xf1,
	0x81, 0xd0, 0x73, 0x92, 0x8a, 0x75, 0xd7, 0xcb, 0x76, 0x02, 0x4c, 0x3f, 0xe1, 0xfb, 0x46, 0x68,
	0xaf, 0x7c, 0x5b, 0x46, 0x22, 0x7f, 0x4d, 0xc8, 0xc1, 0x66, 0x0a, 0x57, 0x1b, 0xed, 0x60, 0xcb,
	0x2d, 0xf9, 0x8b, 0x5b, 0xef, 0x37, 0xb7, 0x6e, 0x43, 0x61, 0xed, 0x71, 0x8a, 0x01, 0xc3, 0x10,
	0xae, 0xbb, 0x5a, 0xa2, 0x34, 0x29, 0x48, 0x7a, 0x13, 0xe2, 0xa2, 0x17, 0x24, 0xc5, 0x57, 0xa3,
	0x47, 0x2c, 0xe6, 0xb9, 0xb5, 0xf0, 0xe1, 0xf1, 0xf7, 0x36, 0x4e, 0x90, 0xff, 0xbb, 0xba, 0x7b,
	0xbc, 0x9d, 0x2b, 0xbf, 0x12, 0x15, 0x93, 0x66, 0xcd, 0x8b, 0xae, 0xab, 0x1f, 0x5a, 0xc7, 0xe5,
	0x4a, 0x81, 0xf6, 0x7c, 0x66, 0xb9, 0x34, 0x16, 0xc6, 0xce, 0x0b, 0xb9, 0x0c, 0xc7, 0x70, 0x62,
	0x73, 0xe5, 0x79, 0xf7, 0x35, 0x61, 0xe6, 0xf8, 0xf0, 0x2a, 0x0d, 0x79, 0x4f, 0xdf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x4d, 0x0e, 0x73, 0x99, 0x68, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FaucetClient is the client API for Faucet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FaucetClient interface {
	// Credit an account
	Credit(ctx context.Context, in *CreditRequest, opts ...grpc.CallOption) (*CreditResponse, error)
}

type faucetClient struct {
	cc *grpc.ClientConn
}

func NewFaucetClient(cc *grpc.ClientConn) FaucetClient {
	return &faucetClient{cc}
}

func (c *faucetClient) Credit(ctx context.Context, in *CreditRequest, opts ...grpc.CallOption) (*CreditResponse, error) {
	out := new(CreditResponse)
	err := c.cc.Invoke(ctx, "/faucet.Faucet/Credit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaucetServer is the server API for Faucet service.
type FaucetServer interface {
	// Credit an account
	Credit(context.Context, *CreditRequest) (*CreditResponse, error)
}

func RegisterFaucetServer(s *grpc.Server, srv FaucetServer) {
	s.RegisterService(&_Faucet_serviceDesc, srv)
}

func _Faucet_Credit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaucetServer).Credit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faucet.Faucet/Credit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaucetServer).Credit(ctx, req.(*CreditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Faucet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "faucet.Faucet",
	HandlerType: (*FaucetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Credit",
			Handler:    _Faucet_Credit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/services/faucet/faucet.proto",
}
