# See https://github.com/maxdome/swagger-combine for this config file usage
swagger: '2.0'
info:
  title: ConsenSys Codefi Orchestrate REST API
  version: latest
  contact:
    name: "ConsenSys Codefi Orchestrate"
    email: "orchestrate@consensys.net"
externalDocs:
  description: "Documentation of ConsenSys Codefi Orchestrate"
  url: "https://docs.orchestrate.consensys.net/"
apis:
  - url: 'public/swagger-specs/services/api/swagger.json'
    tags:
      add:
        - "Orchestrate API"
  - url: 'public/swagger-specs/services/key-manager/swagger.json'
    tags:
      add:
        - "Key Manager"
