{
 "title": "nginx_connections_active",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "nginx_http_requests_total/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nginx_http_requests_total{}[2s])",
     "legendFormat": "delta"
    }
   ]
  },
  {
   "title": "overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_accepted" },
    { "expr": "nginx_connections_handled" },
    { "expr": "nginx_connections_active" },
    { "expr": "nginx_connections_reading" },
    { "expr": "nginx_connections_waiting" },
    { "expr": "nginx_connections_writing" }
   ]
  },
  {
   "title": "nginx_connections_waiting",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_waiting" }
   ]
  },
  {
   "title": "nginx_connections_active",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  }
 ]
}