// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/args/private.proto

package args

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Private arguments
type Private struct {
	// When sending a private transaction, the sending party's base64-encoded public key to use.
	// If not present and passing private_for
	PrivateFrom string `protobuf:"bytes,1,opt,name=private_from,json=privateFrom,proto3" json:"private_from,omitempty"`
	// When sending a private transaction, an array of the recipients' base64-encoded public keys.
	PrivateFor []string `protobuf:"bytes,2,rep,name=private_for,json=privateFor,proto3" json:"private_for,omitempty"`
	// For Quorum >=2.2.1 support
	PrivateTxType        string   `protobuf:"bytes,3,opt,name=private_tx_type,json=privateTxType,proto3" json:"private_tx_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Private) Reset()         { *m = Private{} }
func (m *Private) String() string { return proto.CompactTextString(m) }
func (*Private) ProtoMessage()    {}
func (*Private) Descriptor() ([]byte, []int) {
	return fileDescriptor_e905c5b580b5af7f, []int{0}
}

func (m *Private) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Private.Unmarshal(m, b)
}
func (m *Private) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Private.Marshal(b, m, deterministic)
}
func (m *Private) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Private.Merge(m, src)
}
func (m *Private) XXX_Size() int {
	return xxx_messageInfo_Private.Size(m)
}
func (m *Private) XXX_DiscardUnknown() {
	xxx_messageInfo_Private.DiscardUnknown(m)
}

var xxx_messageInfo_Private proto.InternalMessageInfo

func (m *Private) GetPrivateFrom() string {
	if m != nil {
		return m.PrivateFrom
	}
	return ""
}

func (m *Private) GetPrivateFor() []string {
	if m != nil {
		return m.PrivateFor
	}
	return nil
}

func (m *Private) GetPrivateTxType() string {
	if m != nil {
		return m.PrivateTxType
	}
	return ""
}

func init() {
	proto.RegisterType((*Private)(nil), "args.Private")
}

func init() { proto.RegisterFile("types/args/private.proto", fileDescriptor_e905c5b580b5af7f) }

var fileDescriptor_e905c5b580b5af7f = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x4f, 0x2c, 0x4a, 0x2f, 0xd6, 0x2f, 0x28, 0xca, 0x2c, 0x4b, 0x2c, 0x49, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0x89, 0x29, 0x95, 0x72, 0xb1, 0x07, 0x40, 0x84, 0x85,
	0x14, 0xb9, 0x78, 0xa0, 0x2a, 0xe2, 0xd3, 0x8a, 0xf2, 0x73, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xb8, 0xa1, 0x62, 0x6e, 0x45, 0xf9, 0xb9, 0x42, 0xf2, 0x5c, 0xdc, 0x70, 0x25, 0xf9, 0x45,
	0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0x5c, 0x30, 0x15, 0xf9, 0x45, 0x42, 0x6a, 0x5c, 0xfc,
	0x30, 0x05, 0x25, 0x15, 0xf1, 0x20, 0xbb, 0x25, 0x98, 0xc1, 0xc6, 0xf0, 0x42, 0x85, 0x43, 0x2a,
	0x42, 0x2a, 0x0b, 0x52, 0x9d, 0xec, 0xa2, 0x6c, 0xd2, 0x33, 0x4b, 0x72, 0x12, 0x93, 0xf4, 0x92,
	0xf3, 0x73, 0xf5, 0x9d, 0xf3, 0xf3, 0x8a, 0x53, 0xf3, 0x82, 0x2b, 0x8b, 0xf5, 0x93, 0x73, 0x32,
	0x53, 0xf3, 0x4a, 0xf4, 0xd3, 0x8a, 0xf4, 0x93, 0xf3, 0x8b, 0x52, 0x75, 0x8b, 0x4b, 0x12, 0x93,
	0xb3, 0xf5, 0x0b, 0xb2, 0xd3, 0xf5, 0xd2, 0x33, 0x4b, 0xf4, 0x11, 0x5e, 0x49, 0x62, 0x03, 0xfb,
	0xc1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xa3, 0x96, 0x97, 0xdf, 0x00, 0x00, 0x00,
}
